[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
hoodie = "${RPC_URL_HOODIE}"
mainnet = "${RPC_URL_MAINNET}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# Testing
[fuzz]
runs = 256
max_test_rejects = 65536
seed = "0x1234"
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 256
depth = 15
fail_on_revert = false
